import {TIconLogos} from "@/app/type/type";
import {
    SiHtml5,
    SiCss3,
    SiJavascript,
    SiTypescript,
    SiPhp,
    SiPython,
    SiKotlin,
    SiMysql,
    SiQuasar,
    SiReact,
    SiNextdotjs,
    SiLaravel,
    SiDotnet,
    SiTailwindcss,
    SiBootstrap,
    SiJquery,
    SiSqlalchemy,
    SiGit,
    SiGithub,
    SiGitlab,
    SiDocker,
    SiPostman,
    SiJetbrains,
    SiDbeaver, SiVuedotjs, SiSpring
} from "react-icons/si";
import { FaJava } from "react-icons/fa";
import { TbBrandCSharp } from "react-icons/tb";
import { VscVscode } from "react-icons/vsc";

export const techLogos = [
    { node: <SiHtml5 />, title: "HTML", href: "https://developer.mozilla.org/en-US/docs/Web/HTML" },
    { node: <SiCss3 />, title: "CSS", href: "https://developer.mozilla.org/en-US/docs/Web/CSS" },
    { node: <SiJavascript />, title: "JavaScript", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
    { node: <SiTypescript />, title: "TypeScript", href: "https://www.typescriptlang.org" },
    { node: <SiPhp />, title: "PHP", href: "https://www.php.net" },
    { node: <SiPython />, title: "Python", href: "https://www.python.org" },
    { node: <FaJava />, title: "Java", href: "https://www.java.com" },
    { node: <TbBrandCSharp />, title: "C#", href: "https://learn.microsoft.com/en-us/dotnet/csharp/" },
    { node: <SiKotlin />, title: "Kotlin", href: "https://kotlinlang.org" },
    { node: <SiMysql />, title: "SQL", href: "https://www.mysql.com" },

    { node: <SiVuedotjs />, title: "Vue", href: "https://vuejs.org" },
    { node: <SiQuasar />, title: "Quasar", href: "https://quasar.dev" },
    { node: <SiReact />, title: "React", href: "https://react.dev" },
    { node: <SiNextdotjs />, title: "Next.js", href: "https://nextjs.org" },
    { node: <SiLaravel />, title: "Laravel", href: "https://laravel.com" },
    { node: <SiSpring />, title: "Spring Boot", href: "https://spring.io/projects/spring-boot" },
    { node: <SiDotnet />, title: ".NET", href: "https://dotnet.microsoft.com" },
    { node: <SiTailwindcss />, title: "Tailwind CSS", href: "https://tailwindcss.com" },
    { node: <SiBootstrap />, title: "Bootstrap", href: "https://getbootstrap.com" },
    { node: <SiJquery />, title: "jQuery", href: "https://jquery.com" },
    { node: <SiSqlalchemy />, title: "SQLAlchemy", href: "https://www.sqlalchemy.org" },

    { node: <SiGit />, title: "Git", href: "https://git-scm.com" },
    { node: <SiGithub />, title: "GitHub", href: "https://github.com" },
    { node: <SiGitlab />, title: "GitLab", href: "https://gitlab.com" },
    { node: <SiDocker />, title: "Docker", href: "https://www.docker.com" },
    { node: <SiPostman />, title: "Postman", href: "https://www.postman.com" },
    { node: <VscVscode />, title: "Visual Studio Code", href: "https://code.visualstudio.com" },
    { node: <SiJetbrains />, title: "JetBrains", href: "https://www.jetbrains.com" },
    { node: <SiDbeaver />, title: "DBeaver", href: "https://dbeaver.io" },
];

export const ProgrammingLanguageIconLogos: TIconLogos[] = [
    {
        name: 'HTML',
        color: "bg-gradient-to-r from-orange-400/30 to-red-400/30",
        pathLogo: '/logo/programming_language/html.png',
        width: 50,
        height: 50,
    },
    {
        name: "CSS",
        color: "bg-gradient-to-r from-blue-400/30 to-indigo-400/30",
        pathLogo: '/logo/programming_language/css.png',
        width: 50,
        height: 50,
    },
    {
        name: "JavaScript",
        color: "bg-gradient-to-r from-yellow-200/50 to-orange-400/30",
        pathLogo: '/logo/programming_language/js.png',
        width: 35,
        height: 35,
    },
    {
        name: "TypeScript",
        color: "bg-gradient-to-r from-blue-400/50 to-indigo-400/30",
        pathLogo: '/logo/programming_language/ts.png',
        width: 35,
        height: 35,
    },
    {
        name: 'PHP',
        color: "bg-gradient-to-r from-purple-500/50 to-indigo-400/40",
        pathLogo: '/logo/programming_language/php.png',
        width: 50,
        height: 50,
    },
    {
        name: 'Python',
        color: "bg-gradient-to-r from-yellow-400/40 to-blue-400/40",
        pathLogo: '/logo/programming_language/python.png',
        width: 35,
        height: 35,
    },
    {
        name: 'Java',
        color: "bg-gradient-to-r from-blue-500/40 to-orange-400/20",
        pathLogo: '/logo/programming_language/java.png',
        width: 35,
        height: 35,
    },
    {
        name: 'C#',
        color: "bg-gradient-to-r from-purple-500/50 to-blue-400/50",
        pathLogo: '/logo/programming_language/csharp.png',
        width: 35,
        height: 35,
    },
    {
        name: "kotlin",
        color: "bg-gradient-to-r from-purple-400/30 to-pink-400",
        pathLogo: '/logo/programming_language/kotlin.png',
        width: 50,
        height: 50,
    },
    {
        name: "SQL",
        color: "bg-gradient-to-r from-blue-400/30 to-cyan-400",
        pathLogo: '/logo/programming_language/sql.png',
        width: 50,
        height: 50,
    }
]

export const FrameworkIconLogos: TIconLogos[] = [
    {
        name: "Vue",
        color: "bg-gradient-to-r from-emerald-400/30 to-green-400/30",
        pathLogo: '/logo/libraries_framework/vue.png',
        width: 50,
        height: 50,
    },
    {
        name : "Quasar",
        color: "bg-gradient-to-r from-purple-400/30 to-indigo-400/30",
        pathLogo: '/logo/libraries_framework/quasar.png',
        width: 50,
        height: 50,
    },
    {
        name: "React",
        color: "bg-gradient-to-r from-cyan-400/30 to-blue-400/30",
        pathLogo: '/logo/libraries_framework/react.png',
        width: 50,
        height: 50,
    },
    {
        name: "Next.js",
        color: "bg-gradient-to-r from-gray-500/40 to-black/40",
        pathLogo: '/logo/libraries_framework/nextjs.webp',
        width: 50,
        height: 50,
    },
    {
        name: 'Laravel',
        color: "bg-gradient-to-r from-red-500/40 to-pink-400/40",
        pathLogo: '/logo/libraries_framework/laravel.png',
        width: 80,
        height: 70,
    },
    {
        name: 'Spring Boot',
        color: "bg-gradient-to-r from-green-500/40 to-emerald-400/40",
        pathLogo: '/logo/libraries_framework/springboot.png',
        width: 40,
        height: 40,
    },
    {
        name: '.NET',
        color: "bg-gradient-to-r from-purple-500/40 to-blue-400/40",
        pathLogo: '/logo/libraries_framework/dotnet.png',
        width: 70,
        height: 70,
    },
    {
        name: 'Tornado FX',
        color: "bg-gradient-to-r from-purple-500/40 to-pink-400/40",
        pathLogo: '/logo/libraries_framework/tornadofx.png',
        width: 70,
        height: 70,
    },
    {
        name: 'Tailwind CSS',
        color: "bg-gradient-to-r from-cyan-400/30 to-blue-400/30",
        pathLogo: '/logo/libraries_framework/tailwind.png',
        width: 50,
        height: 50,
    },
    {
        name: 'Bootstrap',
        color: "bg-gradient-to-r from-purple-400/30 to-indigo-400/30",
        pathLogo: '/logo/libraries_framework/bootstrap.png',
        width: 50,
        height: 50,
    },
    {
        name: 'J Query',
        color: "bg-gradient-to-r from-blue-400/30 to-indigo-400/30",
        pathLogo: '/logo/libraries_framework/jquery.png',
        width: 50,
        height: 50,
    },
    {
        name: 'SqlAlchemy',
        color: "bg-gradient-to-r from-blue-400/30 to-indigo-400/30",
        pathLogo: '/logo/libraries_framework/sqlalchemy.png',
        width: 50,
        height: 50,
    },
    {
        name: 'Axios',
        color: "bg-gradient-to-r from-blue-400/30 to-indigo-400/30",
        pathLogo: '/logo/libraries_framework/axios.png',
        width: 50,
        height: 50,
    }
]

export const ToolsIconLogos: TIconLogos[] = [
    {
        name: "Git",
        color: "bg-gradient-to-r from-red-400/30 to-pink-400/30",
        pathLogo: '/logo/tools/git.png',
        width: 50,
        height: 50,
    },
    {
        name: "GitHub",
        color: "bg-gradient-to-r from-gray-500/40 to-black/40",
        pathLogo: '/logo/tools/github.png',
        width: 50,
        height: 50,
    },
    {
        name: "GitLab",
        color: "bg-gradient-to-r from-orange-400/30 to-red-400/30",
        pathLogo: '/logo/tools/gitlab.png',
        width: 50,
        height: 50,
    },
    {
        name: "Docker",
        color: "bg-gradient-to-r from-blue-400/30 to-cyan-400/30",
        pathLogo: '/logo/tools/docker.png',
        width: 50,
        height: 50,
    },
    {
        name: "Postman",
        color: "bg-gradient-to-r from-orange-400/30 to-red-400/30",
        pathLogo: '/logo/tools/postman.webp',
        width: 50,
        height: 50,
    },
    {
        name : 'Visual Studio Code',
        color: "bg-gradient-to-r from-blue-400/30 to-indigo-400/30",
        pathLogo: '/logo/tools/vscode.webp',
        width: 50,
        height: 50,
    },
    {
        name : 'JetBrains',
        color: "bg-gradient-to-r from-purple-400/30 to-pink-400/30",
        pathLogo: '/logo/tools/jetbrains.png',
        width: 50,
        height: 50,
    },
    {
        name : 'DBeaver',
        color: "bg-gradient-to-r from-blue-400/30 to-cyan-400/30",
        pathLogo: '/logo/tools/dbeaver.png',
        width: 50,
        height: 50,
    },
]