import {TProject} from "@/type/type";
export const projects: TProject[] = [
    {
        id: "1",
        title: "DX Trade",
        description: "DX Trade adalah aplikasi desktop yang dikembangkan untuk memfasilitasi aktivitas perdagangan aset digital dan saham secara real-time. Aplikasi ini menyediakan fitur analisis pasar, manajemen portofolio, serta eksekusi transaksi yang cepat dan aman, dengan antarmuka yang intuitif dan responsif.",
        category: "Dekstop App",
        year: "2024",
        image: "/projects/dxtrade.png",
        tags: ["React", "Next.js", "TypeScript", "Stripe"],
        summary: [
            'Fitur analisis pasar',
            'Manajemen portofolio',
            'Eksekusi transaksi yang cepat dan aman',
            'Antarmuka yang intuitif dan responsif',
        ],
        link: "#",
        featured: true,
    },
    {
        id: "2",
        title: "VHS Pertamina",
        description: "VHS Pertamina adalah aplikasi web yang dirancang untuk mendukung proses digitalisasi dan efisiensi operasional di lingkungan Pertamina. Platform ini memfasilitasi pengelolaan data, pemantauan aktivitas, serta pelaporan secara terintegrasi, dengan fokus pada keamanan, kecepatan, dan kemudahan penggunaan.",
        category: "Web App",
        year: "2024",
        image: "/projects/vhs.png",
        tags: ["React Native", "Node.js", "WebRTC", "MongoDB"],
        summary: [
            'Pengelolaan data',
            'Pemantauan aktivitas',
            'Pelaporan secara terintegrasi',
            'Fokus pada keamanan, kecepatan, dan kemudahan penggunaan',
        ],
        link: "#",
        featured: true,
    },
    {
        id: "3",
        title: "PLN",
        description: "proyek data engineering yang berfokus pada pembangunan pipeline data untuk mengintegrasikan dan memproses data operasional dari berbagai sumber internal PLN. Proyek ini bertujuan untuk meningkatkan efisiensi analisis, mendukung pengambilan keputusan berbasis data, serta memastikan ketersediaan data yang akurat dan terstruktur.",
        category: "Data Engineer",
        year: "2024",
        image: "/projects/data.png",
        tags: ["Python", "OpenAI", "FastAPI", "React"],
        summary: [
            'Pembangunan pipeline data',
            'Integrasikan dan memproses data operasional',
            'Efisiensi analisis',
            'Pengambilan keputusan berbasis data',
            'Ketersediaan data yang akurat dan terstruktur',
        ],
        link: "#",
        featured: false,
    },
    {
        id: "4",
        title: "DJKN - Kinerja Badan Usaha",
        description: "DJKN – Kinerja Badan Usaha adalah aplikasi web yang dikembangkan untuk memantau dan mengevaluasi kinerja badan usaha di bawah pengelolaan Direktorat Jenderal Kekayaan Negara (DJKN). Platform ini menyediakan fitur pelaporan, analisis data keuangan, serta visualisasi kinerja secara interaktif untuk mendukung pengambilan keputusan strategis.",
        category: "Web Development",
        year: "2023",
        image: "/projects/kbu.jpg",
        tags: ["Vue.js", "Three.js", "PostgreSQL", "AWS"],
        summary: [
            'Pelaporan',
            'Analisis data keuangan',
            'Visualisasi kinerja secara interaktif',
            'Pengambilan keputusan strategis',
        ],
        link: "#",
        featured: false,
    },
    {
        id: "5",
        title: "Telenofilm",
        description: "Aplikasi management pengelolaan jasa studio photografi",
        category: "Web Development",
        year: "2023",
        image: "/fitness-app-dashboard.png",
        tags: ["Flutter", "Firebase", "HealthKit", "Charts"],
        summary: [
            'Pengelolaan jasa studio',
            'Pengelolaan data pelanggan',
            'Pengelolaan data studio',
            'Pengelolaan data transaksi',
        ],
        link: "#",
        featured: false,
    },
    {
        id: "6",
        title: "Kampoeng Ciherang",
        description: "Sistem informasi managemen pengelolaan tempat wisata kampoeng ciherang",
        category: "Web Development",
        year: "2023",
        image: "/projects/ciherang.png",
        tags: ["React", "Express", "MySQL", "Socket.io"],
        summary: [
            'Pengelolaan data wisata',
            'Pengelolaan data pengunjung',
            'Pengelolaan data transaksi',
            'Pengelolaan data keuangan',
        ],
        link: "#",
        featured: false,
    },
]

export const categories = ["All", "Web Development", "Mobile Development", "AI & Machine Learning"]
